version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"

volumes:
  postgres_data:
